/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kurodev_Example */

#ifndef _Included_org_kurodev_Example
#define _Included_org_kurodev_Example
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kurodev_Example
 * Method:    doStuff
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_kurodev_Example_doStuff
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
