/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kurodev_jpixelgameengine_impl_PixelGameEngineNativeImpl */

#ifndef _Included_org_kurodev_jpixelgameengine_impl_PixelGameEngineNativeImpl
#define _Included_org_kurodev_jpixelgameengine_impl_PixelGameEngineNativeImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kurodev_jpixelgameengine_impl_PixelGameEngineNativeImpl
 * Method:    construct
 * Signature: (IIIIZZZZLorg/kurodev/jpixelgameengine/impl/PixelGameEngineWrapper;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_kurodev_jpixelgameengine_impl_PixelGameEngineNativeImpl_construct
  (JNIEnv *, jclass, jint, jint, jint, jint, jboolean, jboolean, jboolean, jboolean, jobject);

/*
 * Class:     org_kurodev_jpixelgameengine_impl_PixelGameEngineNativeImpl
 * Method:    start
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_kurodev_jpixelgameengine_impl_PixelGameEngineNativeImpl_start
  (JNIEnv *, jclass);

/*
 * Class:     org_kurodev_jpixelgameengine_impl_PixelGameEngineNativeImpl
 * Method:    draw
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_kurodev_jpixelgameengine_impl_PixelGameEngineNativeImpl_draw
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_kurodev_jpixelgameengine_impl_PixelGameEngineNativeImpl
 * Method:    isFocused
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_kurodev_jpixelgameengine_impl_PixelGameEngineNativeImpl_isFocused
  (JNIEnv *, jclass);

/*
 * Class:     org_kurodev_jpixelgameengine_impl_PixelGameEngineNativeImpl
 * Method:    getKey
 * Signature: (I)Lorg/kurodev/jpixelgameengine/input/HWButton;
 */
JNIEXPORT jobject JNICALL Java_org_kurodev_jpixelgameengine_impl_PixelGameEngineNativeImpl_getKey
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_kurodev_jpixelgameengine_impl_PixelGameEngineNativeImpl
 * Method:    getMouse
 * Signature: (I)Lorg/kurodev/jpixelgameengine/input/HWButton;
 */
JNIEXPORT jobject JNICALL Java_org_kurodev_jpixelgameengine_impl_PixelGameEngineNativeImpl_getMouse
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_kurodev_jpixelgameengine_impl_PixelGameEngineNativeImpl
 * Method:    getMouseX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_kurodev_jpixelgameengine_impl_PixelGameEngineNativeImpl_getMouseX
  (JNIEnv *, jclass);

/*
 * Class:     org_kurodev_jpixelgameengine_impl_PixelGameEngineNativeImpl
 * Method:    getMouseY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_kurodev_jpixelgameengine_impl_PixelGameEngineNativeImpl_getMouseY
  (JNIEnv *, jclass);

/*
 * Class:     org_kurodev_jpixelgameengine_impl_PixelGameEngineNativeImpl
 * Method:    getMouseWheel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_kurodev_jpixelgameengine_impl_PixelGameEngineNativeImpl_getMouseWheel
  (JNIEnv *, jclass);

/*
 * Class:     org_kurodev_jpixelgameengine_impl_PixelGameEngineNativeImpl
 * Method:    getWindowMouse
 * Signature: ()Lorg/kurodev/jpixelgameengine/pos/IntegerVector2D;
 */
JNIEXPORT jobject JNICALL Java_org_kurodev_jpixelgameengine_impl_PixelGameEngineNativeImpl_getWindowMouse
  (JNIEnv *, jclass);

/*
 * Class:     org_kurodev_jpixelgameengine_impl_PixelGameEngineNativeImpl
 * Method:    getMousePos
 * Signature: ()Lorg/kurodev/jpixelgameengine/pos/IntegerVector2D;
 */
JNIEXPORT jobject JNICALL Java_org_kurodev_jpixelgameengine_impl_PixelGameEngineNativeImpl_getMousePos
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
