/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kurodev_jpixelgameengine_PixelGameEngineNativeImpl */

#ifndef _Included_org_kurodev_jpixelgameengine_PixelGameEngineNativeImpl
#define _Included_org_kurodev_jpixelgameengine_PixelGameEngineNativeImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kurodev_jpixelgameengine_PixelGameEngineNativeImpl
 * Method:    construct
 * Signature: (IIIIZZZZLorg/kurodev/jpixelgameengine/PixelGameEngineWrapper;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_kurodev_jpixelgameengine_PixelGameEngineNativeImpl_construct
  (JNIEnv *, jclass, jint, jint, jint, jint, jboolean, jboolean, jboolean, jboolean, jobject);

/*
 * Class:     org_kurodev_jpixelgameengine_PixelGameEngineNativeImpl
 * Method:    start
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_kurodev_jpixelgameengine_PixelGameEngineNativeImpl_start
  (JNIEnv *, jclass);

/*
 * Class:     org_kurodev_jpixelgameengine_PixelGameEngineNativeImpl
 * Method:    draw
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_kurodev_jpixelgameengine_PixelGameEngineNativeImpl_draw
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
