name: maven-publish.yml
on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'
          cache: 'maven'

      - name: Get version from pom.xml
        id: get_version

        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Create GitHub tag (If it doesn't exist yet)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag v$VERSION || echo "Tag v$VERSION already exists, skipping tag creation"
          git push origin v$VERSION || echo "Tag v$VERSION already pushed, skipping push"
        env:
          VERSION: ${{ steps.get_version.outputs.version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            🧩 **Maven Dependency (via JitPack)**
            The binary (.dll / .so / .dylib) files should be downloaded automatically on first startup,
            if that doesn't work, however, just create a folder called "lib" and copy the needed file there.
            To use this library via [JitPack](https://jitpack.io), add the following to your `pom.xml`:
            
            ```xml
            <dependencies>
              <dependency>
                <groupId>com.github.kuro-dev</groupId>
                <artifactId>olc-j-pixel-game-engine</artifactId>
                <version>${{ env.VERSION }}</version>
              </dependency>
            </dependencies>
            <repositories>
              <repository>
                <id>jitpack.io</id>
                <url>https://jitpack.io</url>
              </repository>
            </repositories>
            ```
            📁 This release includes compiled `.jar`, `.javadoc.jar`, and native `.so` / `.dll` and `.dylib` files.
          name: Release ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          files: |
            target/*.jar
            target/*.javadoc.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  compile-macos-libraries:
    runs-on: macos-latest
    needs: build-and-release
    steps:
      - uses: actions/checkout@v5
      - name: Build macOS dylib
        run: |
          VERSION=${{ needs.build-and-release.outputs.VERSION }}
          mkdir -p lib
          
          BREW_PREFIX=$(brew --prefix)
          
          clang++ -dynamiclib -std=c++17 -fPIC \
          -DOLC_PGE_APPLICATION -DOLC_PLATFORM_GLUT \
          -DVERSION="\"$VERSION\"" \
          -I${BREW_PREFIX}/include \
          -L${BREW_PREFIX}/lib \
          native/org_kurodev_pixelGameEngineFFM.cpp \
          -lpng \
          -o lib/liborg_kurodev_pixelGameEngineFFM.dylib \
          -framework Cocoa -framework OpenGL

      - name: Upload macOS dylib
        run: gh release upload v${{ needs.build-and-release.outputs.VERSION }} lib/*.dylib --clobber=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  compile-windows-linux-libraries:
    runs-on: ubuntu-latest
    needs: build-and-release
    steps:
      - uses: actions/checkout@v5
      - name: Build Linux & Windows libraries via Docker
        run: |
          mkdir -p lib
          docker build -o . .

      - name: Upload Linux & Windows libraries to release
        run: gh release upload v${{ needs.build-and-release.outputs.VERSION }} lib/* --clobber=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}