name: maven-publish.yml
on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  macos-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build macOS dylib
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          mkdir -p lib
          clang++ -dynamiclib -std=c++17 -fPIC \
            -DOLC_PGE_APPLICATION -DOLC_PLATFORM_GLUT \
            -DVERSION="\"$VERSION\"" \
            native/org_kurodev_pixelGameEngineFFM.cpp \
            -o lib/liborg_kurodev_pixelGameEngineFFM.dylib \
            -framework Cocoa -framework OpenGL
      - name: Upload macOS dylib artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-lib
          path: lib/*.dylib
  windows-linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build native libraries via Docker
        run: |
          # Build Linux and Windows shared libraries
          mkdir -p lib
          docker build -o . .
      - name: Upload Docker artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docker-libs
          path: lib/*.so,lib/*.dll

  upload-libs:
    runs-on: ubuntu-latest
    needs: [ macos-build, windows-linux-build ]
    steps:
      - name: Download macOS artifact
        uses: actions/download-artifact@v3
        with:
          name: macos-lib
          path: macos-lib

      - name: Download Docker artifacts
        uses: actions/download-artifact@v3
        with:
          name: docker-libs
          path: docker-libs

      - name: Merge artifacts
        run: |
          mkdir -p lib
          cp macos-lib/*.dylib lib/
          cp docker-libs/*.so lib/
          cp docker-libs/*.dll lib/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}